sudo: required
services:
  - docker

#testing done only for the react-app. if we have tests for the worker/express
#also more lines can be added in before_install & script sections for each of them.
before_install:
  - docker build -t container_id -f ./fib_app_frontend/Dockerfile.dev ./fib_app_frontend
script:
  - docker run container_id npm run test -- --coverage

#after building the above 'production' images push them to docker hub below.
  #one has to mention kanand/ while tagging the image so that when
  #image push to docker hub is successfull. It sort of tells the path
  #where to store the image on docker hub
  #(e.g. [docker.io/[secure]/server_api] <--- this is travis output)
after_success:
  - docker build -t kanand/fib_app_frontend ./fib_app_frontend
  - docker build -t kanand/nginx ./nginx
  - docker build -t kanand/server_api ./server_api
  - docker build -t kanand/worker ./worker
  #login into the docker CLI
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
  #after successful login above push the images to the docker hub
  - docker push kanand/fib_app_frontend
  - docker push kanand/nginx
  - docker push kanand/server_api
  - docker push kanand/worker

deploy:
  provider: elasticbeanstalk
  region: ap-south-1
  app: multi_container_docker
  env: MultiContainerDocker-env
  bucket_name: elasticbeanstalk-ap-south-1-630684117158
  bucket_path: multi_container_docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  